apiVersion: v1
kind: Service
metadata:
  name: heroes-service
spec:
  type: ClusterIP
  selector:
    app: heroes
  ports:
    - port: 8080           # 서비스에서 사용하는 포트
      targetPort: 8080      # 컨테이너에서 사용하는 포트
      protocol: TCP