apiVersion: v1
kind: Service
metadata:
  name: heroes-frontend-service
spec:
  type: NodePort
  selector:
    app: heroes-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
      protocol: TCP
